#!/usr/bin/env python
import argparse
import pandas as pd 


def main(input_file,output):
    pd_data =  pd.read_csv(input_file, sep = "\t"  )
    import pdb
    bigger =  pd_data.loc[pd_data['Kinship'] > coefficient ]
    
    for i in pd_data['FID']:

        pdb.set_trace()
        print "test"
    
    with open(output,'w') as w:
        for index, row in bigger.iterrows():
            w.write("{}\t{}\n".format(row['FID'],row['ID1']))

    print "Output written to {}".format(output)
    
if __name__ == "__main__":
    # Command line arguments
    parser = argparse.ArgumentParser("""Converts FlashPCA output into SmartPCA output
    """)
    parser.add_argument("-i", "--input", default = 'king.kin', 
help="Input file from FlashPCA to convert to SmartPCA output format.")
    parser.add_argument("-o", "--output", default = 'pca.evec', 
help="Name of Outputfile.")
args = parser.parse_args() 
main(args.input, args.output)
